version: '2'
services:
  backend:
    container_name: backend
    build:
      context: ./local-env/app-server/
    restart: always
    volumes:
      - ./infra_crawler:/infra_crawler
      - static_volume:/infra_crawler/app/staticfiles

volumes:
  static_volume:
