version: '2'
services:
  plantuml-server:
    image: plantuml/plantuml-server:jetty
    ports:
      - 8080:8080
    environment:
      - BASE_URL=plantuml

  app:
    container_name: django-app
    depends_on:
      - plantuml-server
    build:
      context: ./local-env/app-server/
    expose:
      - 8000
    env_file:
      - ./.env
    restart: always
    volumes:
      - ./infra_crawler:/infra_crawler
      - static_volume:/infra_crawler/app/staticfiles

volumes:
  static_volume:
