on:
  push:
    branches-ignore:
      - master
  

permissions:
  contents: write

jobs:
  update-architecture:
    runs-on: ubuntu-latest
    name: Update archtiecture diagram
    steps:
      - name: Invoke infragenie to commit the diagram
        uses: Rikenunes8/infragenie-ghaction@master
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          host: 'https://1874-94-132-118-62.ngrok-free.app'
          readme: true
